from dotenv import load_dotenv
import os

load_dotenv()

# Fuelling station
PI_IP = os.getenv('PI_IP')
MQTT_BROKER_PORT = os.getenv('MQTT_BROKER_PORT')
MQTT_BROKER_PORT = int(MQTT_BROKER_PORT)
FUELLING_STATION_PI_IP = os.getenv('FUELLING_STATION_PI_IP')
FUELLING_STATION_PI_HTTP_PORT = os.getenv('FUELLING_STATION_PI_HTTP_PORT')
FUELLING_STATION_PI_HTTP_PORT = int(FUELLING_STATION_PI_HTTP_PORT)

# Mission control
HOST_LAPTOP_IP = os.getenv('HOST_LAPTOP_IP')
GROUND_STATION_HOST_IP = os.getenv('GROUND_STATION_HOST_IP')

# Misc
HEARTBEAT_INTERVAL = os.getenv('HEARTBEAT_INTERVAL') # seconds between sending heartbeats - keep as integer vals
HEARTBEAT_INTERVAL = int(HEARTBEAT_INTERVAL)

COMMAND_TIMEOUT_INTERVAL = os.getenv('COMMAND_TIMEOUT_INTERVAL') # seconds between upload commands timing out - keep as integer vals
COMMAND_TIMEOUT_INTERVAL = int(COMMAND_TIMEOUT_INTERVAL)

RESEND_FAILED_CAN_INTERVAL = os.getenv('RESEND_FAILED_CAN_INTERVAL') # seconds between resending can messages (can be ms)
RESEND_FAILED_CAN_INTERVAL = float(RESEND_FAILED_CAN_INTERVAL)
RESEND_FAILED_CAN_COUNT = os.getenv('RESEND_FAILED_CAN_COUNT')
RESEND_FAILED_CAN_COUNT = int(RESEND_FAILED_CAN_COUNT)

# User set variables
# - For initialising ox vent
OX_VENT_UPPER_BOUND = os.getenv('OX_VENT_UPPER_BOUND')
OX_VENT_UPPER_BOUND = int(OX_VENT_UPPER_BOUND)
OX_VENT_LOWER_BOUND = os.getenv('OX_VENT_LOWER_BOUND')
OX_VENT_LOWER_BOUND = int(OX_VENT_LOWER_BOUND)
OX_VENT_OPEN_PERCENTAGE = os.getenv('OX_VENT_OPEN_PERCENTAGE')
OX_VENT_OPEN_PERCENTAGE = int(OX_VENT_OPEN_PERCENTAGE)
# - For initialising engine ignition
IGNITER_START_DELAY = os.getenv('IGNITER_START_DELAY')
IGNITER_START_DELAY = float(IGNITER_START_DELAY)
OX_FILL_SET_OPEN_PERCENTAGE = os.getenv('OX_FILL_SET_OPEN_PERCENTAGE')
OX_FILL_SET_OPEN_PERCENTAGE = int(OX_FILL_SET_OPEN_PERCENTAGE)
OX_FILL_VALVE_OPEN_ANGLE = os.getenv('OX_FILL_VALVE_OPEN_ANGLE')
OX_FILL_VALVE_OPEN_ANGLE = int(OX_FILL_VALVE_OPEN_ANGLE)
CHAMBER_MAX_PRESSURE_TIME_LIMIT = os.getenv('CHAMBER_MAX_PRESSURE_TIME_LIMIT')
CHAMBER_MAX_PRESSURE_TIME_LIMIT = float(CHAMBER_MAX_PRESSURE_TIME_LIMIT)

# CAN IDs

# Heartbeats
SEND_HB_FUELLING_TO_ROCKET = os.getenv('SEND_HB_FUELLING_TO_ROCKET')
RECEIVE_HB_FUELLING_TO_ROCKET = os.getenv('RECEIVE_HB_FUELLING_TO_ROCKET')
RECEIVE_HB_INDIVIDUAL_BOARDS_LV = os.getenv('RECEIVE_HB_INDIVIDUAL_BOARDS_1')
RECEIVE_HB_INDIVIDUAL_BOARDS_GS = os.getenv('RECEIVE_HB_INDIVIDUAL_BOARDS_2')

# Servos
OX_PRESSURE_ID = os.getenv('OX_PRESSURE_ID')
OX_VENT_ID = os.getenv('OX_VENT_ID')
ETH_VENT_ID = os.getenv('ETH_VENT_ID')
OX_OUT_ID = os.getenv('OX_OUT_ID')
ETH_OUT_ID = os.getenv('ETH_OUT_ID')
GS_OX_IN_ID = os.getenv('GS_OX_IN_ID')
GS_N2_IN_ID = os.getenv('GS_N2_IN_ID')
GS_N2_VENT_ID = os.getenv('GS_N2_VENT_ID')
GS_OX_VENT_ID = os.getenv('GS_OX_VENT_ID')
OX_AND_ETH_SIMULTANEOUSLY_ID = os.getenv('OX_AND_ETH_SIMULTANEOUSLY_ID')

# Controller gains
SEND_KP_ID = os.getenv('SEND_KP_ID')
RECEIVE_KP_ID = os.getenv('RECEIVE_KP_ID')
SEND_KI_ID = os.getenv('SEND_KI_ID')
RECEIVE_KI_ID = os.getenv('RECEIVE_KI_ID')
SEND_KD_ID = os.getenv('SEND_KD_ID')
RECEIVE_KD_ID = os.getenv('RECEIVE_KD_ID')

# Pressure transducers
RECEIVE_PT_LV_N2_AND_ETH = os.getenv('RECEIVE_PT_LV_N2_AND_ETH')
RECEIVE_PT_LV_N20 = os.getenv('RECEIVE_PT_LV_N20')
RECEIVE_PT_LV_4_AND_5 = os.getenv('RECEIVE_PT_LV_4_AND_5')
RECEIVE_PT_LV_6 = os.getenv('RECEIVE_PT_LV_6')

RECEIVE_PT_GS_1_AND_2 = os.getenv('RECEIVE_PT_GS_1_AND_2')
RECEIVE_PT_GS_3_AND_4 = os.getenv('RECEIVE_PT_GS_3_AND_4')

# Thermocouples
RECEIVE_TC_1_AND_2 = os.getenv('RECEIVE_TC_1_AND_2')
RECEIVE_TC_3_AND_4 = os.getenv('RECEIVE_TC_3_AND_4')

# Flight controller
SEND_EMERGENCY_STOP = os.getenv('SEND_EMERGENCY_STOP')
RECEIVE_EMERGENCY_STOP = os.getenv('RECEIVE_EMERGENCY_STOP')
SEND_FIRE_IGNITER = os.getenv('SEND_FIRE_IGNITER')
RECEIVE_FIRE_IGNITER = os.getenv('RECEIVE_FIRE_IGNITER')
SEND_HANDOFF_CONTROL = os.getenv('SEND_HANDOFF_CONTROL')
RECEIVE_HANDOFF_CONTROL = os.getenv('RECEIVE_HANDOFF_CONTROL')
SEND_RETAKE_CONTROL = os.getenv('SEND_RETAKE_CONTROL')
RECEIVE_RETAKE_CONTROL = os.getenv('RECEIVE_RETAKE_CONTROL')
SEND_INIT_OXVENT = os.getenv('SEND_INIT_OXVENT')
RECEIVE_INIT_OXVENT = os.getenv('RECEIVE_INIT_OXVENT')
SEND_INIT_ENGINE_IGNITION = os.getenv('SEND_INIT_ENGINE_IGNITION')
RECEIVE_INIT_ENGINE_IGNITION = os.getenv('RECEIVE_INIT_ENGINE_IGNITION')